Split BasicDataFormatDescriptorHeader off from BasicDataFormatDescriptor
BVE-Reborn/ktx2 pull request #11
Opened 2022-09-05 04:34 UTC by LPGhatguy

## Checklist

- [x] `cargo clippy` reports no issues
- [x] `cargo doc` reports no issues
- [x] [`cargo deny`](https://github.com/EmbarkStudios/cargo-deny/) issues have been fixed or added to `deny.toml`
- [x] `cargo test` shows all tests passing
- [x] human-readable change descriptions added to the changelog under the "Unreleased" heading.
  - [x] If the change does not affect the user (or is a process change), preface the change with "Internal:"
  - [ ] Add credit to yourself for each change: `Added new functionality @githubname`.

## Description
This PR splits the header information from `BasicDataInformationDescriptor` into its own type to make way for encoding and decoding it separately.

2022-09-05 05:47 UTC, Ralith requested changes

2022-09-05 05:47 UTC, Ralith commented on src/lib.rs
> +    pub sample_data: &'data [u8],
Let's expose this as `sample_information` for consistency with the spec.

2022-09-05 07:25 UTC, Ralith commented on src/dfds.rs
> +//! Data Format Definitions for defined image formats.
Stray add?

2022-09-05 07:33 UTC, LPGhatguy commented on src/dfds.rs
> +//! Data Format Definitions for defined image formats.
Whoops!

2022-09-05 07:43 UTC, Ralith approved these changes

2022-09-06 17:46 UTC, Ralith commented
Rebase needed.

2022-09-06 23:01 UTC, cwfitzgerald approved these changes

2022-09-06 23:01 UTC, merged